bird_species = [
    # Iconic Endemics & National Symbols
    "Javan Hawk-Eagle (Nisaetus bartelsi)",
    "Bali Myna (Leucopsar rothschildi)",
    "Maleo (Macrocephalon maleo)",
    "Rhinoceros Hornbill (Buceros rhinoceros)",
    "Helmeted Hornbill (Rhinoplax vigil)",
    "Sulawesi Hornbill (Rhabdotorrhinus exarhatus)",
    "Javan Green Magpie (Cissa thalassina)",
    "Black-winged Myna (Acridotheres melanopterus)",

    # Sumatra
    "Sumatran Laughingthrush (Garrulax bicolor)",
    "Sumatran Ground Cuckoo (Carpococcyx sumatranus)",
    "Sumatran Broadbill (Calyptomena viridis)",
    "Schneider's Pitta (Hydrornis schneideri)",
    "Graceful Pitta (Erythropitta venusta)",
    "Sumatran Trogon (Apalharpactes mackloti)",
    "Blue-masked Leafbird (Chloropsis venusta)",
    "Cream-striped Bulbul (Pycnonotus leucogrammicus)",
    "Sumatran Drongo (Dicrurus sumatranus)",
    "Rajah Scops Owl (Otus brookii)",
    "Salvadori’s Pheasant (Lophura inornata)",
    "Black-capped Kingfisher (Halcyon pileata)",

    # Java
    "Javan Banded Pitta (Hydrornis guajanus)",
    "Javan Trogon (Apalharpactes reinwardtii)",
    "Javan Kingfisher (Halcyon cyanoventris)",
    "Javan Owlet (Glaucidium castanopterum)",
    "Javan Scops Owl (Otus angelinae)",
    "Javan Fulvetta (Alcippe pyrrhoptera)",
    "Javan Tesia (Tesia superciliaris)",
    "Javan White-eye (Zosterops flavus)",
    "Javan Plover (Charadrius javanicus)",
    "Sunda Teal (Anas gibberifrons)",
    "Java Sparrow (Lonchura oryzivora)",
    "Javan Myna (Acridotheres javanicus)",

    # Bali & Lesser Sundas
    "Flores Hawk-Eagle (Nisaetus floris)",
    "Timor Green Pigeon (Treron psittaceus)",
    "Yellow-crested Cockatoo (Cacatua sulphurea)",
    "Wallace's Hanging Parrot (Loriculus flosculus)",
    "Sumba Hornbill (Rhyticeros everetti)",
    "Sumba Buttonquail (Turnix everetti)",
    "Flores Scops Owl (Otus alfredi)",
    "Rote Boobook (Ninox rotiensis)",
    "Timor Imperial Pigeon (Ducula cineracea)",

    # Kalimantan (Borneo)
    "Bornean Bristlehead (Pityriasis gymnocephala)",
    "Bornean Peacock-Pheasant (Polyplectron schleiermacheri)",
    "Bulwer's Pheasant (Lophura bulweri)",
    "Dayak Blue Flycatcher (Cyornis montanus)",
    "White-fronted Falconet (Microhierax latifrons)",
    "Bornean Blue Flycatcher (Cyornis superbus)",
    "Black-browed Babbler (Malacocincla perspicillata)",
    "Bornean Ground Cuckoo (Carpococcyx radiceus)",
    "Blue-headed Pitta (Hydrornis baudii)",
    "Hose's Broadbill (Calyptomena hosei)",

    # Sulawesi & Wallacea
    "Knobbed Hornbill (Rhyticeros cassidix)",
    "Sulawesi Dwarf Kingfisher (Ceyx fallax)",
    "Purple-bearded Bee-eater (Meropogon forsteni)",
    "Sulawesi Masked Owl (Tyto rosenbergii)",
    "Ivory-backed Woodswallow (Artamus monachus)",
    "Piping Crow (Corvus typicus)",
    "Geomalia (Geomalia heinrichi)",
    "Grey-sided Flowerpecker (Dicaeum celebicum)",
    "Sulawesi Tarictic Hornbill (Penelopides exarhatus)",
    "Sulawesi Serpent Eagle (Spilornis rufipectus)",
    "Wallace’s Standardwing (Semioptera wallacii)",
    "Moluccan Cockatoo (Cacatua moluccensis)",

    # Papua (Western New Guinea)
    "Victoria Crowned Pigeon (Goura victoria)",
    "Southern Cassowary (Casuarius casuarius)",
    "Palm Cockatoo (Probosciger aterrimus)",
    "Eclectus Parrot (Eclectus roratus)",
    "King Bird-of-Paradise (Cicinnurus regius)",
    "Greater Bird-of-Paradise (Paradisaea apoda)",
    "Twelve-wired Bird-of-Paradise (Seleucidis melanoleucus)",
    "Raggiana Bird-of-Paradise (Paradisaea raggiana)",
    "Wilson's Bird-of-Paradise (Diphyllodes respublica)",
    "Red Bird-of-Paradise (Paradisaea rubra)",
    "Magnificent Riflebird (Ptiloris magnificus)",
    "Papuan Lorikeet (Charmosyna papou)",
    "Papuan Frogmouth (Podargus papuensis)",
    "Blyth's Hornbill (Rhyticeros plicatus)",
    "New Guinea Harpy Eagle (Harpyopsis novaeguineae)",
    "Brown-headed Crow (Corvus fuscicapillus)",
    "Black Butcherbird (Melloria quoyi)",
    "Golden Monarch (Carterornis chrysomela)",
    "Frilled Monarch (Arses telescophthalmus)",
    "Hooded Pitohui (Pitohui dichrous)",
    "Cinnamon Ground Dove (Gallicolumba rufigula)",

    # Widespread Species
    "Changeable Hawk-Eagle (Nisaetus cirrhatus)",
    "Brahminy Kite (Haliastur indus)",
    "Black Eagle (Ictinaetus malaiensis)",
    "Crested Serpent Eagle (Spilornis cheela)",
    "Collared Kingfisher (Todiramphus chloris)",
    "Stork-billed Kingfisher (Pelargopsis capensis)",
    "Common Kingfisher (Alcedo atthis)",
    "Green Imperial Pigeon (Ducula aenea)",
    "Pied Imperial Pigeon (Ducula bicolor)",
    "Emerald Dove (Chalcophaps indica)",
    "Blue-tailed Bee-eater (Merops philippinus)",
    "Rainbow Bee-eater (Merops ornatus)",
    "Olive-backed Sunbird (Cinnyris jugularis)",
    "Crimson Sunbird (Aethopyga siparaja)",
    "Sunda Scops Owl (Otus lempiji)",
    "Brown Hawk-Owl (Ninox scutulata)",
    "Blyth’s Frogmouth (Batrachostomus affinis)",
    "Pacific Swift (Apus pacificus)",
    "Painted Stork (Mycteria leucocephala)",
    "Lesser Adjutant (Leptoptilos javanicus)",
    "Asian Openbill (Anastomus oscitans)",
    "Milky Stork (Mycteria cinerea)",
    "Lesser Whistling Duck (Dendrocygna javanica)",
    "Black-winged Stilt (Himantopus himantopus)",
    "Pacific Golden Plover (Pluvialis fulva)",
    "Common Myna (Acridotheres tristis)",
    "Hill Myna (Gracula religiosa)",
    "Oriental Magpie-Robin (Copsychus saularis)",
    "Dollarbird (Eurystomus orientalis)",
    "Black-naped Oriole (Oriolus chinensis)",
    "Pink-necked Green Pigeon (Treron vernans)",
    "Zebra Dove (Geopelia striata)",
    "Glossy Ibis (Plegadis falcinellus)",
    "Black-naped Tern (Sterna sumatrana)",
    "Van Hasselt’s Sunbird (Leptocoma brasiliana)",
    "Purple-throated Sunbird (Leptocoma sperata)",
    "Great Eared Nightjar (Lyncornis macrotis)",
    "Glossy Swiftlet (Collocalia esculenta)",
    "Nicobar Pigeon (Caloenas nicobarica)",
    "Red Lory (Eos bornea)",
    "Chattering Lory (Lorius garrulus)",
    "Coconut Lorikeet (Trichoglossus haematodus)",
    "Blue-backed Parrot (Tanygnathus sumatranus)",
    "Pied Kingfisher (Ceryle rudis)",
    "Asian Woollyneck (Ciconia episcopus)",
    "Spotted Wood Owl (Strix seloputo)",
    "Wallace’s Hawk-Eagle (Nisaetus nanus)"
]
