[tool.aerich]
tortoise_orm = "config.TORTOISE_ORM"
location = "./migrations"
src_folder = "./."

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.coverage.run]
omit = ["tests/*", "*/__init__.py", 'database/db_schema.py']

[tool.coverage.report]
show_missing = true