name: Backend Tests and Coverage

on:
  push:
    paths:
      - 'Application/Backend/**'
  pull_request:
    paths:
      - 'Application/Backend/**'
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12  # set your version here

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Application/Backend/requirements.txt
    
    - name: Prepare environment file
      working-directory: Application/Backend
      run: mv .env.sample .env

    - name: Run tests with coverage
      working-directory: Application/Backend
      if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.head_ref != github.base_ref)
      run: |
        pytest --cov --cov-branch --cov-report=xml --junitxml=junit.xml -o junit_family=legacy

    - name: Upload coverage to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/codecov-action@v5
      with:
        files: Application/Backend/coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: kisenaa/birdy-app
        fail_ci_if_error: true

    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/test-results-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
