name: Backend Tests and Coverage

on:
  push:
    paths:
      - 'app/backend/**'
  pull_request:
    paths:
      - 'app/backend/**'
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12  # set your version here

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Application/Backend/requirements.txt

    - name: Run tests with coverage
      if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.head_ref != github.base_ref)
      run: |
        pytest --cov=Application/Backend --cov-report=xml

    - name: Upload coverage to Codecov
      if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.head_ref != github.base_ref)
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.xml
        fail_ci_if_error: true
